# ======================================= #
# ============= Main Menu =============== #
# ======================================= #
[[mainmenu]]
name = "Home"
url = "/"
weight = 1

[[mainmenu]]
name = "About"
url = "/about"
weight = 2

[[mainmenu]]
name = "Posts"
url = "/posts"
weight = 3

[[mainmenu]]
name = "Contact"
url = "/contact"
weight = 4

# ======================================= #
# ============ Footer Menu ============== #
# ======================================= #
[[footermenu]]
name = "Tags"
url = "/tags"
weight = 1

[[footermenu]]
name = "Section"
url = "/section"
weight = 2

[[footermenu]]
name = "Series"
url = "/series"
weight = 3

[[footermenu]]
name = "Newsletter"
url = "/newsletter"
weight = 4
