# ======================================= #
# ============= Main Menu =============== #
# ======================================= #
[[mainmenu]]
name = "Home"
url = "/"
weight = 1

[[mainmenu]]
name = "About"
url = "/about"
weight = 2

[[mainmenu]]
name = "Posts"
url = "/posts"
weight = 3

[[mainmenu]]
name = "Contact"
url = "/contact"
weight = 4
